//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtiruz.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshic
    {
        public int Nomer_cheta { get; set; }
        public string Data { get; set; }
        public string Srok_Postavki { get; set; }
        public string Kol_tovara { get; set; }
        public string Cena { get; set; }
        public int Tovar { get; set; }
        public Nullable<int> Postavshik { get; set; }
    
        public virtual Postavshiki Postavshiki { get; set; }
        public virtual Tovars Tovars { get; set; }
    }
}
